name: Deploy Notifications Trigger Lambda

on:
  push:
    paths:
      - 'root/notifications/send_notification_trigger.py'
    branches:
      - main

jobs:
  lambda-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Function
        run: |
          echo "Zipping deployment package..."
          cd root/notifications
          zip -r deployment_package.zip send_notification_trigger.py
          echo "Updating lambda Function..."
          aws lambda update-function-code --function-name send-notification-trigger --zip-file fileb://./deployment_package.zip
          echo "Done."
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1